name: Nightly CrocoGallery Notebook Check

on:
  schedule:
    - cron: '0 8 * * *'  
  workflow_dispatch:      # allow manual trigger too
  push:

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/crocodile-cesm/crocodash:nightly
    steps:
      - name: Checkout CrocoGallery
        uses: actions/checkout@v4

      - name: Run signature checks
        run: python .github/scripts/check_notebook_signatures.py gallery/notebooks
