name: Run Quality Control

on: [push, pull_request, workflow_dispatch]

jobs:
  check_paths:
    runs-on: ubuntu-latest
    steps:

        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Run Quality Control
          run: |
            .github/scripts/quality_control_notebooks.sh
  check-notebook-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pyyaml -e .
      - name: Check all notebooks (except exclusions) are in run_notebooks.yml matrix
        run: |
          bash .github/scripts/check_notebook_coverage.sh